import "./globals.css";

export const metadata = {
  title: "YakChat Text Summariser",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/yak.ico" />
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}
